Add impersonation support to send_packet service
zxdavb/ramses_cc pull request #194
Opened 2024-06-17 18:41 UTC by Kars-de-Jong

This change adds support for impersonation using the send_packet service.

I use it to send fan_demand packets from my faked CO2 sensor, because ramses_rf doesn't support that yet.

2024-06-17 20:20 UTC, zxdavb requested changes
Very good - some minor changes please, and we can merge.

2024-06-17 20:20 UTC, zxdavb commented on tests/test_services.py
> +        "37:123456": {"class": "FAN"}
In order of device_id, please.
```python
        "32:139773": {"class": "HUM"},
        "37:123456": {"class": "FAN"},
        "40:123456": {"class": "REM", "faked": True},
```

2024-06-17 20:20 UTC, zxdavb commented on custom_components/ramses_cc/translations/en.json
> +                    "send_packet": "Enable send_packet service for sending bespoke packets",
```
"Enable send_packet service for casting bespoke packets"
```

2024-06-17 20:20 UTC, zxdavb commented on custom_components/ramses_cc/services.yaml
> +        If not specified, the device ID of the gateway is used.
```text
Optional: if not specified, the device ID of the gateway is used.
```

2024-06-19 08:12 UTC, Kars-de-Jong commented
@zxdavb I processed your comments, could you have another look?

2024-06-20 20:06 UTC, zxdavb commented
@Kars-de-Jong I'm curious - why couldn't you solve this use-case with a remote?

2024-06-21 07:30 UTC, Kars-de-Jong commented
That's a good question... I just assumed the HRU needs to see both co2_level and fan_demand packets from the same device.

2024-08-19 10:07 UTC, closed without merging